### ISSUE TITLE
Employment Object

### ISSUE THREAD

**Issue by jmenglis** [TaylorOD/taylorod.github.io#1]
I figured I would drop this here as a way to give you an issue in Github 😄 

There is an issue with the object below that would cause you to only have one name and one position listed if you were to hypothetically run this code that makes up your bio.
```
employment: {
  name: "SoupSonic",
  position: "Software Engineer / Partner",
  name: "Ancilla Partners",
  position: "Full Stack Ruby / JavaScript Developer"
},
```

hint:
```
const x = { a: "hello", a: "hi" };

console.log(x)
//  { a: "hi" }
```

**Comment by TaylorOD** [comment]
Haha! You are correct. Good catch. Just pushed a fix.
